CREATE TABLE EVENTO(
	NOME 		VARCHAR2(30) NOT NULL,
	DATA 		DATE NOT NULL, 
	TIPO 		VARCHAR2(20) NOT NULL, 
	CONSTRAINT 	PK_EVENTO PRIMARY KEY(NOME, DATA), 
	CHECK 		(UPPER(TIPO) IN ('FESTA', 'CONFRATERNIZACAO'))  
);

CREATE TABLE REPUBLICA(
	NOME 		VARCHAR2(30) NOT NULL, 
	ENDERECO 	VARCHAR2(40), 
	PRECOH 		FLOAT(126), 
	LOTACAO 	NUMBER(5), 
	TAMANHO 	NUMBER(4), 

	CONSTRAINT 	PK_REPUBLICA PRIMARY KEY (NOME)
);

CREATE TABLE FESTA(
	NOME 		VARCHAR2(30) NOT NULL,
	DATA 		DATE NOT NULL, 
	REPUBLICA 	VARCHAR2(30),
	CONSTRAINT	PK_FESTA PRIMARY KEY (NOME, DATA),	 
	CONSTRAINT	FK1_FESTA FOREIGN KEY (NOME, DATA) REFERENCES EVENTO(NOME, DATA)
		ON DELETE CASCADE,
	CONSTRAINT	FK2_FESTA FOREIGN KEY (REPUBLICA) REFERENCES REPUBLICA(NOME)
		ON DELETE SET NULL 
);

CREATE TABLE PROPRIETARIOREP(
	REPUBLICA 	VARCHAR2(30) NOT NULL,
	NOME 		VARCHAR2(20) NOT NULL,
	CONSTRAINT 	PK_PROPRIETARIOREP PRIMARY KEY (REPUBLICA, NOME),
	CONSTRAINT 	FK_PROPRIETARIOREP FOREIGN KEY (REPUBLICA) REFERENCES REPUBLICA(NOME)
		ON DELETE CASCADE
);

CREATE TABLE CASAFESTA(
	NOME		VARCHAR2(30) NOT NULL, 
	CNPJ 		NUMBER(14) NOT NULL, 
	ENDERECO	VARCHAR2(40),
	PRECOH		FLOAT(126),
	LOTACAO		NUMBER(5),
	TAMANHO 	NUMBER(4), 
	CONSTRAINT	PK_CASAFESTA PRIMARY KEY (NOME), 
	UNIQUE(CNPJ)
);

CREATE TABLE CONFRATERNIZACAO(
	NOME 		VARCHAR2(30) NOT NULL,
	DATA 		DATE NOT NULL, 
	CASAFESTA	VARCHAR(30),	 
	CONSTRAINT 	PK_CONFRATERNIZACAO PRIMARY KEY (NOME, DATA),	 
	CONSTRAINT	FK1_CONFRATERNIZACAO FOREIGN KEY (NOME, DATA) REFERENCES EVENTO(NOME, DATA)
		ON DELETE CASCADE, 
	CONSTRAINT 	FK2_CONFRATERNIZACAO FOREIGN KEY (CASAFESTA) REFERENCES CASAFESTA(NOME)
		ON DELETE SET NULL
);	

CREATE TABLE CONVIDADO(
	CPF			NUMBER(13) NOT NULL, 
	NOME		VARCHAR2(20),	 
	UNIVERSIDADE VARCHAR2(30),	 
	TIPOU		NUMBER(1),	
	TIPOJ		NUMBER(1),	 
	DATANASC	DATE,  
	CONSTRAINT	PK_CONVIDADO PRIMARY KEY (CPF),	 
	CHECK		(UPPER(TIPOU) IN (0, 1)),	
	CHECK		(UPPER(TIPOJ) IN (0, 1))
);

CREATE TABLE JOGADOR(
	CPF			NUMBER(13) NOT NULL, 
	TIME		VARCHAR2(20),	 
	MODALIDADE	VARCHAR2(20),	 
	CONSTRAINT 	PK_JOGADOR PRIMARY KEY (CPF),	 
	CONSTRAINT	FK_JOGADOR FOREIGN KEY (CPF) REFERENCES CONVIDADO(CPF)
		ON DELETE CASCADE
);

CREATE TABLE UNIVERSITARIO(
	CPF			NUMBER(13) NOT NULL, 
	CONSTRAINT	PK_UNIVERSITARIO PRIMARY KEY (CPF),	
	CONSTRAINT	FK_UNIVERSITARIO FOREIGN KEY (CPF) REFERENCES CONVIDADO(CPF)
		ON DELETE CASCADE
);

CREATE TABLE MOTORISTA(
	CNH			NUMBER(11) NOT NULL,
	NOME		VARCHAR2(20),	 
	CONSTRAINT	PK_MOTORISTA PRIMARY KEY (CNH)
);

CREATE TABLE TRANSPORTE(
	PLACA		VARCHAR2(7) NOT NULL, 
	MODELO		VARCHAR2(20),	 
	CONSTRAINT	PK_TRANSPORTE PRIMARY KEY (PLACA)
);

CREATE TABLE CONDUCAO(
	MOTORISTA 	NUMBER(11) NOT NULL,
	TRANSPORTE 	VARCHAR2(7) NOT NULL,
	DATA 		DATE NOT NULL, 
	CONSTRAINT	PK_CONDUCAO PRIMARY KEY (MOTORISTA, TRANSPORTE, DATA),	 
	CONSTRAINT	FK1_CONDUCAO FOREIGN KEY (MOTORISTA) REFERENCES MOTORISTA(CNH)
		ON DELETE CASCADE, 
	CONSTRAINT FK2_CONDUCAO FOREIGN KEY (TRANSPORTE) REFERENCES TRANSPORTE(PLACA)
		ON DELETE CASCADE
);

CREATE TABLE VIAGEM(
	JOGADOR 	NUMBER(13) NOT NULL, 
	TRANSPORTE 	VARCHAR2(7) NOT NULL,
	CONF 		VARCHAR2(30) NOT NULL,
	DATACONF 	DATE NOT NULL,
	DATAHORA	DATE NOT NULL, 
	CONSTRAINT	PK_VIAGEM PRIMARY KEY (JOGADOR, TRANSPORTE, DATAHORA),	 
	CONSTRAINT 	FK1_VIAGEM FOREIGN KEY (JOGADOR) REFERENCES JOGADOR(CPF)
		ON DELETE CASCADE, 
	CONSTRAINT 	FK2_VIAGEM FOREIGN KEY (TRANSPORTE) REFERENCES TRANSPORTE(PLACA)
		ON DELETE CASCADE, 
	CONSTRAINT	FK3_VIAGEM FOREIGN KEY (CONF, DATACONF) REFERENCES CONFRATERNIZACAO(NOME, DATA)
		ON DELETE CASCADE
);

CREATE TABLE TRAJETO(
	UNIVERSITARIO NUMBER(13) NOT NULL, 
	TRANSPORTE 	VARCHAR2(7) NOT NULL,
	FESTA 		VARCHAR2(30) NOT NULL,
	DATAFESTA	DATE NOT NULL,
	DATAHORA	DATE NOT NULL, 
	CONSTRAINT	PK_TRAJETO PRIMARY KEY (UNIVERSITARIO, TRANSPORTE, DATAHORA),	 
	CONSTRAINT 	FK1_TRAJETO FOREIGN KEY (UNIVERSITARIO) REFERENCES UNIVERSITARIO(CPF)
		ON DELETE CASCADE, 
	CONSTRAINT 	FK2_TRAJETO FOREIGN KEY (TRANSPORTE) REFERENCES TRANSPORTE(PLACA)
		ON DELETE CASCADE, 
	CONSTRAINT	FK3_TRAJETO FOREIGN KEY (FESTA, DATAFESTA) REFERENCES FESTA(NOME, DATA)
		ON DELETE CASCADE
);

CREATE TABLE SEGURANCA(
	CPF			NUMBER(13) NOT NULL, 
	NOME		VARCHAR2(30),	 
	CONSTRAINT	PK_SEGURANCA PRIMARY KEY (CPF) 
);

CREATE TABLE SEGURANCATRABALHA(
	SEGURANCA 	NUMBER(13) NOT NULL, 
	EVENTO 		VARCHAR2(30) NOT NULL, 
	DATA 		DATE NOT NULL, 
	CONSTRAINT 	PK_SEGURANCATRABALHA PRIMARY KEY (SEGURANCA, EVENTO, DATA),	 
	CONSTRAINT 	FK_SEGURANCATRABALHA FOREIGN KEY (EVENTO, DATA) REFERENCES EVENTO(NOME, DATA)
		ON DELETE CASCADE
);

CREATE TABLE DJ(
	CPF			NUMBER(13) NOT NULL,
	NOME		VARCHAR2(30),	 
	PRECOH		FLOAT(126),	 
	ESTILO		VARCHAR2(20),	
	CONSTRAINT 	PK_DJ PRIMARY KEY (CPF)
);

CREATE TABLE DJPERFORMA(
	DJ 			NUMBER(13) NOT NULL,
	EVENTO 		VARCHAR2(30) NOT NULL, 
	DATA 		DATE NOT NULL, 
	CONSTRAINT 	PK_DJPERFORMA PRIMARY KEY (DJ, EVENTO, DATA),	
	CONSTRAINT 	FK_DJPERFORMA FOREIGN KEY (EVENTO, DATA) REFERENCES EVENTO(NOME, DATA)
		ON DELETE CASCADE  
);

CREATE TABLE FOODTRUCK(
	CNPJ		NUMBER(14) NOT NULL,
	NOME		VARCHAR2(30),	 
	CONSTRAINT	PK_FOODTRUCK PRIMARY KEY (CNPJ)
);

CREATE TABLE COMIDASFT(
	FOODTRUCK 	NUMBER(14) NOT NULL, 
	COMIDA 		VARCHAR(20) NOT NULL,
	PRECO 		FLOAT(126),	 
	CONSTRAINT 	PK_COMIDASFT PRIMARY KEY (FOODTRUCK, COMIDA),	
	CONSTRAINT	FK_COMIDASFT FOREIGN KEY (FOODTRUCK) REFERENCES FOODTRUCK(CNPJ)
		ON DELETE CASCADE
);

CREATE TABLE PROPRIETARIOFT(
	FOODTRUCK 	NUMBER(14) NOT NULL,
	NOME		VARCHAR2(30) NOT NULL, 
	TELEFONE	NUMBER(12),	
	CONSTRAINT 	PK_PROPRIETARIOFT PRIMARY KEY (FOODTRUCK, NOME),	 
	CONSTRAINT 	FK_PROPRIETARIOFT FOREIGN KEY (FOODTRUCK) REFERENCES FOODTRUCK(CNPJ) 
);

CREATE TABLE COMIDAFESTA(
	FOODTRUCK 	NUMBER(14) NOT NULL, 
	FESTA 		VARCHAR2(30) NOT NULL,
	DATA 		DATE NOT NULL, 
	CONSTRAINT 	PK_COMIDAFESTA PRIMARY KEY (FOODTRUCK, FESTA, DATA),	 
	CONSTRAINT	FK1_COMIDAFESTA FOREIGN KEY (FOODTRUCK) REFERENCES FOODTRUCK(CNPJ)
		ON DELETE CASCADE, 
	CONSTRAINT 	FK2_COMIDAFESTA FOREIGN KEY (FESTA, DATA) REFERENCES FESTA(NOME, DATA)
		ON DELETE CASCADE
);

CREATE TABLE BUFFET(
	CNPJ 		NUMBER(14) NOT NULL,
	NOME		VARCHAR(30),	 
	CONSTRAINT 	PK_BUFFET PRIMARY KEY (CNPJ)
);

CREATE TABLE PRATOSQUENTES(
	BUFFET 		NUMBER(14) NOT NULL, 
	PRATO 		VARCHAR2(20) NOT NULL, 
	CONSTRAINT 	PK_PRATOSQUENTES PRIMARY KEY (BUFFET, PRATO),	 
	CONSTRAINT	FK_PRATOSQUENTES FOREIGN KEY (BUFFET) REFERENCES BUFFET(CNPJ)
		ON DELETE CASCADE
);


CREATE TABLE ACOMPANHAMENTOS(
	BUFFET 		NUMBER(14) NOT NULL, 
	ACOMP 		VARCHAR2(20) NOT NULL, 
	CONSTRAINT 	PK_ACOMPANHAMENTOS PRIMARY KEY (BUFFET, ACOMP),	 
	CONSTRAINT	FK_ACOMPANHAMENTOS FOREIGN KEY (BUFFET) REFERENCES BUFFET(CNPJ)
		ON DELETE CASCADE
);


CREATE TABLE SALADAS(
	BUFFET 		NUMBER(14) NOT NULL, 
	SALADA 		VARCHAR2(20) NOT NULL, 
	CONSTRAINT 	PK_SALADAS PRIMARY KEY (BUFFET, SALADA),	 
	CONSTRAINT	FK_SALADAS FOREIGN KEY (BUFFET) REFERENCES BUFFET(CNPJ)
		ON DELETE CASCADE
);


CREATE TABLE PROPRIETARIOBUF(
	BUFFET 		NUMBER(14) NOT NULL, 
	NOME 		VARCHAR2(20) NOT NULL, 
	TELEFONE 	NUMBER(12),	 
	CONSTRAINT 	PK_PROPRIETARIOBUF PRIMARY KEY (BUFFET, NOME),	 
	CONSTRAINT	FK_PROPRIETARIOBUF FOREIGN KEY (BUFFET) REFERENCES BUFFET(CNPJ)
		ON DELETE CASCADE
);

CREATE TABLE COMIDACONF(
	BUFFET 		NUMBER(14) NOT NULL, 
	CONF 		VARCHAR2(30) NOT NULL, 
	DATA 		DATE NOT NULL, 
	CONSTRAINT 	PK_COMIDACONF PRIMARY KEY (BUFFET, CONF, DATA),	 
	CONSTRAINT 	FK_COMIDACONF FOREIGN KEY (CONF, DATA) REFERENCES CONFRATERNIZACAO(NOME, DATA)
		ON DELETE CASCADE
);

CREATE TABLE BEBIDA(
	NOME		VARCHAR2(20) NOT NULL, 
	CONTEUDO	NUMBER(4),	
	PRECO 		FLOAT(126),	 
	CONSTRAINT 	PK_BEBIDA PRIMARY KEY (NOME)
);

CREATE TABLE BEBIDASERVIDA(
	BEBIDA 		VARCHAR2(20) NOT NULL,
	EVENTO 		VARCHAR2(30) NOT NULL,
	DATA 		DATE NOT NULL, 
	CONSTRAINT 	PK_BEBIDASERVIDA PRIMARY KEY (BEBIDA, EVENTO, DATA),	 
	CONSTRAINT 	FK_BEBIDASERVIDA FOREIGN KEY (EVENTO, DATA) REFERENCES EVENTO(NOME, DATA)
		ON DELETE CASCADE 
);

CREATE TABLE MEDALHA(
	CONF 		VARCHAR2(30) NOT NULL,
	DATA    	DATE NOT NULL,
	MODALIDADE	VARCHAR2(20) NOT NULL,
	COLOCACAO	NUMBER(1) NOT NULL, 
	COR 		VARCHAR2(20),	 
	JOGADOR 	NUMBER(13),	 
	CONSTRAINT 	PK_MEDALHA PRIMARY KEY (CONF, DATA, COLOCACAO, MODALIDADE),	 
	CONSTRAINT 	FK1_MEDALHA FOREIGN KEY (CONF, DATA) REFERENCES CONFRATERNIZACAO(NOME, DATA)
		ON DELETE CASCADE, 
	CONSTRAINT 	FK2_MEDALHA FOREIGN KEY (JOGADOR) REFERENCES JOGADOR(CPF)
		ON DELETE CASCADE
);

CREATE TABLE PULSEIRA(
	NUMERO		NUMBER(10) NOT NULL, 
	COR 		VARCHAR2(20),	 
	CONVIDADO 	NUMBER(13),	 
	EVENTO 		VARCHAR2(30),	 
	DATA 		DATE, 
	CONSTRAINT 	PK_PULSEIRA PRIMARY KEY (NUMERO),	 
	CONSTRAINT 	FK1_PULSEIRA FOREIGN KEY (CONVIDADO) REFERENCES CONVIDADO(CPF)
		ON DELETE CASCADE, 
	CONSTRAINT 	FK2_PULSEIRA FOREIGN KEY (EVENTO, DATA) REFERENCES EVENTO(NOME, DATA)
		ON DELETE CASCADE
);
